<?xml version="1.0" encoding="utf-8"?><Database Name="haroen.viaeneeurospacecenter" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.129.28.188\SQL_WEBSPACES;Initial Catalog=haroen.viaeneeurospacecenter;Persist Security Info=True;User ID=haroen.viaeneharoen.viaene" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="haroen_viaeneeurospacecenterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="[haroen.viaeneharoen.viaene].users_has_parkplans" Member="users_has_parkplans">
    <Type Name="users_has_parkplan">
      <Column Name="accepted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="users_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="parkplans_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="parkplan_users_has_parkplan" Member="parkplan" ThisKey="parkplans_id" OtherKey="id" Type="parkplan" IsForeignKey="true" />
      <Association Name="user_users_has_parkplan" Member="user" ThisKey="users_id" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="[haroen.viaeneharoen.viaene].activations" Member="activations">
    <Type Name="activation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="users_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="user_activation" Member="user" ThisKey="users_id" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="[haroen.viaeneharoen.viaene].attractions" Member="attractions">
    <Type Name="attraction">
      <Column Name="item_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="min_height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="max_height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="item_attraction" Member="item" ThisKey="item_id" OtherKey="id" Type="item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="[haroen.viaeneharoen.viaene].items" Member="items">
    <Type Name="item">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="item_attraction" Member="attractions" ThisKey="id" OtherKey="item_id" Type="attraction" />
      <Association Name="item_parkplans_has_item" Member="parkplans_has_items" ThisKey="id" OtherKey="items_id" Type="parkplans_has_item" />
      <Association Name="item_rating" Member="ratings" ThisKey="id" OtherKey="items_id" Type="rating" />
      <Association Name="item_restaurant" Member="restaurants" ThisKey="id" OtherKey="items_id" Type="restaurant" />
      <Association Name="item_show" Member="shows" ThisKey="id" OtherKey="items_id" Type="show" />
    </Type>
  </Table>
  <Table Name="[haroen.viaeneharoen.viaene].parkplans" Member="parkplans">
    <Type Name="parkplan">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="parkplan_users_has_parkplan" Member="users_has_parkplans" ThisKey="id" OtherKey="parkplans_id" Type="users_has_parkplan" />
      <Association Name="parkplan_parkplans_has_item" Member="parkplans_has_items" ThisKey="id" OtherKey="parkplans_id" Type="parkplans_has_item" />
    </Type>
  </Table>
  <Table Name="[haroen.viaeneharoen.viaene].parkplans_has_items" Member="parkplans_has_items">
    <Type Name="parkplans_has_item">
      <Column Name="parkplans_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="items_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="item_parkplans_has_item" Member="item" ThisKey="items_id" OtherKey="id" Type="item" IsForeignKey="true" />
      <Association Name="parkplan_parkplans_has_item" Member="parkplan" ThisKey="parkplans_id" OtherKey="id" Type="parkplan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="[haroen.viaeneharoen.viaene].ratings" Member="ratings">
    <Type Name="rating">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="users_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="items_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="rating" Member="rating1" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="item_rating" Member="item" ThisKey="items_id" OtherKey="id" Type="item" IsForeignKey="true" />
      <Association Name="user_rating" Member="user" ThisKey="users_id" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="[haroen.viaeneharoen.viaene].restaurants" Member="restaurants">
    <Type Name="restaurant">
      <Column Name="items_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="payment_type" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="item_restaurant" Member="item" ThisKey="items_id" OtherKey="id" Type="item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="[haroen.viaeneharoen.viaene].shows" Member="shows">
    <Type Name="show">
      <Column Name="items_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="item_show" Member="item" ThisKey="items_id" OtherKey="id" Type="item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="[haroen.viaeneharoen.viaene].users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="admin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="user_users_has_parkplan" Member="users_has_parkplans" ThisKey="id" OtherKey="users_id" Type="users_has_parkplan" />
      <Association Name="user_activation" Member="activations" ThisKey="id" OtherKey="users_id" Type="activation" />
      <Association Name="user_rating" Member="ratings" ThisKey="id" OtherKey="users_id" Type="rating" />
    </Type>
  </Table>
</Database>